# Generated by Django 4.0.7 on 2022-09-20 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=200)),
                ('scan_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SubDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subDomain_name', models.CharField(max_length=100)),
                ('ip', models.CharField(blank=True, max_length=200, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StartScan.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=800)),
                ('source_url', models.URLField(max_length=800)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StartScan.domain')),
            ],
        ),
        migrations.CreateModel(
            name='DomainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrar', models.CharField(max_length=800)),
                ('creation_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('ip_address', models.CharField(max_length=200)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StartScan.domain')),
            ],
        ),
    ]
