# Generated by Django 4.0.7 on 2022-09-20 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StartScan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaininfo',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StartScan.domain'),
        ),
        migrations.AlterField(
            model_name='source',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StartScan.domain'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StartScan.domain'),
        ),
    ]
