# Generated by Django 4.0.7 on 2022-09-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StartScan', '0002_alter_domaininfo_domain_alter_source_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaininfo',
            name='creation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='domaininfo',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='domaininfo',
            name='update_date',
            field=models.DateTimeField(null=True),
        ),
    ]
