# Generated by Django 4.0.7 on 2022-09-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StartScan', '0003_alter_domaininfo_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaininfo',
            name='registrar',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
