# Generated by Django 4.0.7 on 2022-09-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StartScan', '0004_alter_domaininfo_registrar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubDomain',
        ),
    ]
