# Generated by Django 4.0.7 on 2022-09-26 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StartScan', '0005_delete_subdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subDomain_name', models.CharField(max_length=100)),
                ('ip', models.CharField(blank=True, max_length=200, null=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StartScan.domain')),
            ],
        ),
    ]
