# Generated by Django 4.0.7 on 2022-09-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StartScan', '0006_subdomain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubDomain',
        ),
    ]
