# Generated by Django 4.0.7 on 2022-09-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StartScan', '0008_subdomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaininfo',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='source',
            name='domain',
        ),
        migrations.AddField(
            model_name='domain',
            name='ip_address',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='source',
            field=models.ManyToManyField(to='StartScan.source'),
        ),
    ]
