# Generated by Django 4.0.7 on 2022-09-26 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StartScan', '0009_remove_domaininfo_ip_address_remove_source_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaininfo',
            name='source',
        ),
    ]
