# Generated by Django 4.0.7 on 2022-10-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StartScan', '0010_remove_domaininfo_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaininfo',
            name='source',
            field=models.ManyToManyField(to='StartScan.source'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='subDomain_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
