# Generated by Django 4.0.7 on 2022-10-06 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StartScan', '0011_domaininfo_source_alter_domain_domain_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=800)),
                ('source_url', models.URLField(max_length=800)),
            ],
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='ip_address',
            new_name='ip_adress',
        ),
        migrations.RenameField(
            model_name='domaininfo',
            old_name='domain',
            new_name='domain_id',
        ),
        migrations.RenameField(
            model_name='subdomain',
            old_name='domain',
            new_name='domain_id',
        ),
        migrations.RemoveField(
            model_name='domaininfo',
            name='source',
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='ip',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.AddField(
            model_name='sourceused',
            name='domain_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StartScan.domain'),
        ),
        migrations.AddField(
            model_name='sourceused',
            name='subdomain_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StartScan.subdomain'),
        ),
    ]
