# Generated by Django 4.1.2 on 2022-10-06 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StartScan', '0012_sourceused_rename_ip_address_domain_ip_adress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateField()),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StartScan.subdomain')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=800)),
                ('tool_url', models.URLField(max_length=800)),
                ('tool_desciption', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='domaininfo',
            old_name='domain_id',
            new_name='domain',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='scan_date',
        ),
        migrations.DeleteModel(
            name='SourceUsed',
        ),
        migrations.AddField(
            model_name='foundfrom',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StartScan.tool'),
        ),
    ]
