# Generated by Django 4.1.2 on 2022-11-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StartScan', '0014_rename_domain_id_subdomain_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaininfo',
            name='creation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='domaininfo',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='domaininfo',
            name='update_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_desciption',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_name',
            field=models.CharField(max_length=800, unique=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_url',
            field=models.URLField(max_length=800, unique=True),
        ),
    ]
