# Generated by Django 4.1.2 on 2022-11-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StartScan', '0015_alter_domaininfo_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tool_desciption',
            field=models.TextField(),
        ),
    ]
