# Generated by Django 4.1.2 on 2022-11-21 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StartScan', '0017_remove_foundfrom_subdomain_remove_foundfrom_tool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=800, unique=True)),
                ('tool_url', models.URLField(max_length=800, unique=True)),
                ('tool_desciption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subDomain_name', models.CharField(max_length=100, unique=True)),
                ('ip', models.CharField(blank=True, max_length=800, null=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StartScan.domain')),
            ],
        ),
        migrations.CreateModel(
            name='FoundFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateField()),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StartScan.subdomain')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StartScan.tool')),
            ],
        ),
        migrations.CreateModel(
            name='DomainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrar', models.CharField(max_length=800, null=True)),
                ('creation_date', models.DateField(null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('update_date', models.DateField(null=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StartScan.domain')),
            ],
        ),
    ]
