# Generated by Django 4.1.2 on 2022-12-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StartScan', '0018_tool_subdomain_foundfrom_domaininfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaininfo',
            name='dnssec',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='status',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
